name: Townhouse275
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10646
title: "Bay Ridge, Brooklyn's First Mixology Bar"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040308'
    - '#fffef6'
    - '#b2b290'
    - '#a48358'
    - '#0038be'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
